// <auto-generated />
namespace Matthewpbalieydesigns.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class customers_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customers_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202008051827286_customers_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
