// <auto-generated />
namespace Matthewpbalieydesigns.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Cart_Setup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cart_Setup));
        
        string IMigrationMetadata.Id
        {
            get { return "202007281944091_Cart_Setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
